#This is a basic workflow for build and deploying with the master branch now, but we can add multiple steps for other
#branches as well as.

#start with actions.
name: Build & Deploy
#control when the action will run.
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

#allow you to run this workflow manually from the actions tab
  workflow_dispatch:

#A work run is made up of one or more jobs that can  run sequentially or in parallel
jobs:
  #this job contains a single job called 'build/lint'
  lint:
    #the type of runner that the job will run on
    runs-on: ubuntu-latest

    #steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the code
      #checkout repository under $GITHUB_WORKSPACE, so job can access it
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
                java-version: '17'
                distribution: 'temurin'

      #add gradlew permission
      - name: Set execute permission on gradlew
        run: chmod +x ./gradlew

      - name: Clean Project
        run: ./gradlew clean

      #This is a Gradle task that runs the Android Lint tool on the code for the debug build
      #variant. Android Lint is a static code analysis tool that checks your Android project
      #for potential issues, such as code errors, performance problems, security vulnerabilities,
      #and best practices
      - name: Build with Lint
        run: ./gradlew lintDebug

      - name: Assemble Debug
        run: ./gradlew assembleDebug

      #upload the test report
      - name: Upload html test report
        uses: actions/upload-artifact@v2
        with:
          name: index.html
          path: app/build/reports/lint-results-debug.html
